version: "3.8"

services:
  consul:
    image: hashicorp/consul:1.19
    container_name: consul
    restart: unless-stopped
    ports:
      - "${CONSUL_PORT}:8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1","log_level":"INFO"}

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cron:
    build:
      context: .
      dockerfile: ./dockerfiles/cron/Dockerfile
    container_name: cron
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./cron:/cron
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      echo '59 23 28-31 * * [ "$$(date +%%d -d tomorrow)" == "01" ] && /cron/rotate_partitions.sh >> /var/log/cron.log 2>&1' >> /etc/crontab &&
      touch /var/log/cron.log &&
      cron -f

  migrator:
    image: migrate/migrate
    container_name: migrator
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  minio:
    container_name: minio
    image: 'quay.io/minio/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET_NAME}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - consul
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana-service
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - consul
      - prometheus

volumes:
  consul-data:
  postgres_data:
  minio_data: